# Clustering Neighborhood Toronto (Part 2)

In [5]:
# Installing and importing Libraries

!pip install geocoder

import pandas as pd
import numpy as np
import geocoder
from geopy.geocoders import Nominatim

print('Imported!')

Requirement already satisfied: geocoder in c:\users\familia\anaconda3\envs\cya\lib\site-packages (1.38.1)
Requirement already satisfied: requests in c:\users\familia\anaconda3\envs\cya\lib\site-packages (from geocoder) (2.23.0)
Requirement already satisfied: six in c:\users\familia\anaconda3\envs\cya\lib\site-packages (from geocoder) (1.15.0)
Requirement already satisfied: ratelim in c:\users\familia\anaconda3\envs\cya\lib\site-packages (from geocoder) (0.1.6)
Requirement already satisfied: click in c:\users\familia\anaconda3\envs\cya\lib\site-packages (from geocoder) (7.1.2)
Requirement already satisfied: future in c:\users\familia\anaconda3\envs\cya\lib\site-packages (from geocoder) (0.18.2)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\familia\anaconda3\envs\cya\lib\site-packages (from requests->geocoder) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\familia\anaconda3\envs\cya\lib\site-packages (from requests->geocoder) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\familia\anaconda3\envs\cya\lib\site-packages (from requests->geocoder) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in c:\users\familia\anaconda3\envs\cya\lib\site-packages (from requests->geocoder) (2.9)
Requirement already satisfied: decorator in c:\users\familia\anaconda3\envs\cya\lib\site-packages (from ratelim->geocoder) (4.4.2)
Imported!

In [17]:
# Importing the data from Part 1
df = pd.read_csv('toronto_data.csv')
df

,Postal Code,Borough,Neighborhood
0,M1B,Scarborough,"Malvern, Rouge"
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
2,M1E,Scarborough,"Guildwood, Morningside, West Hill"
3,M1G,Scarborough,Woburn
4,M1H,Scarborough,Cedarbrae
...,...,...,...
98,M9N,York,Weston
99,M9P,Etobicoke,Westmount
100,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ..."
101,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest..."
102,M9W,Etobicoke,"Northwest, West Humber - Clairville"

In [16]:
geospatial_coordinates = pd.read_csv('Geospatial_coordinates.csv')
geospatial_coordinates

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [18]:
# Using merge to fusion both data frames
df = pd.merge(df, geospatial_coordinates, on='Postal Code')
df

,Postal Code,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
...,...,...,...,...,...
98,M9N,York,Weston,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,43.696319,-79.532242
100,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...",43.688905,-79.554724
101,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
102,M9W,Etobicoke,"Northwest, West Humber - Clairville",43.706748,-79.594054

In [19]:
df.to_csv('toronto_data_part2.csv', index=False)